# Generated by Django 3.2 on 2021-04-26 09:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myblog', '0008_auto_20210426_0915'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='katekoria',
            field=models.CharField(choices=[('Python', 'Python'), ('C++', 'C++'), ('C', 'C')], default='C', max_length=255),
        ),
    ]
